// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnWIeXq5vcBAteM_OI50g5j_Q9D77h7KQ',
    appId: '1:365746228480:web:25316387ccc866da5137e5',
    messagingSenderId: '365746228480',
    projectId: 'allen-f1c51',
    authDomain: 'allen-f1c51.firebaseapp.com',
    databaseURL: 'https://allen-f1c51-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'allen-f1c51.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvAc1gZeDjYrGq3pnLj4ldNmhAubwcbXg',
    appId: '1:365746228480:android:7a50a2f7c6be905b5137e5',
    messagingSenderId: '365746228480',
    projectId: 'allen-f1c51',
    databaseURL: 'https://allen-f1c51-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'allen-f1c51.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZtKlF4aD0XxaTIby17KRw0D_ThOFi8sk',
    appId: '1:365746228480:ios:024ab914ed4ca5195137e5',
    messagingSenderId: '365746228480',
    projectId: 'allen-f1c51',
    databaseURL: 'https://allen-f1c51-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'allen-f1c51.appspot.com',
    androidClientId: '365746228480-smkj8cm2i4e6ud81o8tvvekud67v3cn3.apps.googleusercontent.com',
    iosClientId: '365746228480-ja4lj3g60i5nvatf9gabud532v5d7btn.apps.googleusercontent.com',
    iosBundleId: 'com.musharaf.allen.allen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZtKlF4aD0XxaTIby17KRw0D_ThOFi8sk',
    appId: '1:365746228480:ios:58fd62f263b8520b5137e5',
    messagingSenderId: '365746228480',
    projectId: 'allen-f1c51',
    databaseURL: 'https://allen-f1c51-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'allen-f1c51.appspot.com',
    androidClientId: '365746228480-smkj8cm2i4e6ud81o8tvvekud67v3cn3.apps.googleusercontent.com',
    iosClientId: '365746228480-j8c9ue7fb3i30l2qnqns7mk8g68ni293.apps.googleusercontent.com',
    iosBundleId: 'com.musharaf.allen.allen.RunnerTests',
  );
}
